import fs from 'node:fs'
import path from 'node:path'
import { docsRoot, frontmatter, walk } from './content-utils.mjs'

const plans = {
  'avaliacao/banco-de-questoes.md': ['Defina a arquitetura das categorias|Separe questões por finalidade, área e nível de reutilização.', 'Crie e identifique as questões|Use nomes internos claros, enunciado completo, resposta, nota e feedback.', 'Revise versões e estado|Confirme a versão usada e evite editar sem avaliar tentativas existentes.', 'Pré-visualize antes de reutilizar|Teste cada questão e suas variações fora da avaliação real.'],
  'avaliacao/calculo-e-agregacao.md': ['Traduza o plano em uma regra|Liste itens, notas máximas, pesos e tratamento de valores vazios.', 'Escolha a agregação|Compare a regra publicada com os métodos disponíveis na categoria.', 'Simule casos extremos|Calcule exemplos com zero, ausência, nota máxima e item vazio.', 'Confira a visão do estudante|Verifique subtotais, total e arredondamento no relatório do usuário.'],
  'avaliacao/categorias-e-itens.md': ['Liste as avaliações do curso|Relacione cada atividade a um único item de nota esperado.', 'Crie categorias com finalidade|Agrupe itens apenas quando houver subtotal ou regra compartilhada.', 'Mova e ordene os itens|Faça a estrutura acompanhar o plano apresentado à turma.', 'Revise itens manuais e vinculados|Identifique origem, nota máxima, peso e visibilidade de cada item.'],
  'avaliacao/feedback-e-tentativas.md': ['Defina a função da nova tentativa|Diferencie correção, recuperação, prática e reenvio.', 'Escreva feedback acionável|Aponte evidência, melhoria necessária e próxima ação.', 'Configure reabertura e revisão|Escolha quando o estudante poderá tentar novamente e o que verá.', 'Teste o ciclo completo|Simule tentativa, devolutiva, nova tentativa e resultado final.'],
  'avaliacao/importar-gift.md': ['Prepare uma categoria de destino|Crie a categoria antes da importação e registre a finalidade do lote.', 'Valide a sintaxe GIFT|Revise delimitadores, respostas, feedback, codificação e caracteres especiais.', 'Importe um lote pequeno|Use primeiro questões fictícias para identificar erros de interpretação.', 'Pré-visualize cada questão|Corrija enunciado, nota e feedback antes de inserir em Questionário.'],
  'avaliacao/prazos-e-excecoes.md': ['Mapeie todas as datas|Diferencie abertura, entrega, limite, fechamento e data esperada.', 'Registre a necessidade da exceção|Use apenas a informação mínima e preserve a justificativa conforme a política.', 'Configure usuário ou grupo|Altere somente os campos necessários e confira precedência entre exceções.', 'Teste calendário e acesso|Verifique a nova condição com o perfil afetado sem alterar a turma inteira.'],
  'avaliacao/rubricas-e-guias.md': ['Transforme critérios em dimensões|Escreva aspectos observáveis e sem sobreposição.', 'Defina níveis ou descritores|Diferencie qualidade com linguagem específica e coerente.', 'Configure a pontuação|Confira pesos, nota máxima e conversão para a atividade.', 'Aplique a um exemplo|Avalie uma produção fictícia e revise ambiguidades antes de publicar.'],
  'boas-praticas/acessibilidade.md': ['Percorra somente com teclado|Verifique foco visível, ordem, acionamento e ausência de armadilhas.', 'Revise estrutura e linguagem|Confira títulos, listas, links descritivos e instruções independentes de cor.', 'Valide imagens e mídia|Adicione texto alternativo, legenda, transcrição e controles acessíveis.', 'Teste zoom e tela estreita|Garanta leitura sem corte ou rolagem horizontal desnecessária.'],
  'boas-praticas/comunicacao-e-engajamento.md': ['Declare presença e tempo de resposta|Explique canais, horários, prioridades e expectativa realista.', 'Escreva chamadas para ação|Diga o que fazer, onde, até quando e como obter ajuda.', 'Distribua oportunidades de participação|Combine formatos síncronos, assíncronos e alternativas acessíveis.', 'Revise sinais de acompanhamento|Use evidências com cautela e faça contato sem julgamento antecipado.'],
  'boas-praticas/design-e-organizacao.md': ['Mapeie o percurso principal|Defina a sequência que o estudante deve reconhecer na página do curso.', 'Padronize nomes e seções|Use verbos, títulos paralelos e quantidade previsível de itens.', 'Reduza carga visual|Agrupe o que pertence junto e remova repetição ou decoração sem função.', 'Teste orientação e retomada|Peça a uma conta de teste para localizar a próxima ação e retornar ao ponto anterior.'],
  'boas-praticas/privacidade-e-uso-responsavel.md': ['Minimize os dados usados|Colete e exiba somente o necessário para a finalidade pedagógica.', 'Revise público e permissões|Confirme quem pode ver, editar, exportar ou compartilhar cada informação.', 'Prepare exemplos fictícios|Remova nomes, fotos, identificadores, notas e metadados de capturas.', 'Registre incidentes pelo canal correto|Preserve evidências sem ampliar a exposição e siga a política institucional.'],
  'comece-por-aqui/acessar-plataforma.md': ['Confirme o endereço oficial|Use o link divulgado pela instituição e verifique domínio e conexão segura.', 'Entre pelo método autorizado|Informe credenciais somente na página institucional e conclua autenticação adicional.', 'Reconheça o painel inicial|Confirme nome da conta, cursos esperados e avisos de acesso.', 'Registre um problema com segurança|Anote horário, mensagem e navegador sem enviar senha ou token.'],
  'comece-por-aqui/conhecer-moodle-5-2.md': ['Identifique a versão do ambiente|Consulte a informação disponível ou solicite confirmação à equipe responsável.', 'Compare mudanças relevantes|Priorize navegação, conclusão, atividades e fluxos usados pela instituição.', 'Valide tema e idioma|Confirme onde os controles aparecem no pacote e no tema implantados.', 'Atualize orientações locais|Registre diferenças antes de produzir prints ou vídeos.'],
  'comece-por-aqui/navegar-no-moodle.md': ['Localize o Painel e Meus cursos|Diferencie visão geral pessoal da página de cada curso.', 'Reconheça índice e navegação|Use seções, trilha e controles anterior e próximo para manter contexto.', 'Encontre calendário e notificações|Confira prazos e mensagens sem depender apenas de e-mail.', 'Retome uma atividade|Volte ao curso e identifique estado, conclusão e próxima ação.'],
  'comece-por-aqui/o-que-e-o-moodle.md': ['Reconheça o espaço institucional|Diferencie o Moodle oficial de páginas externas e ambientes de teste.', 'Distinga recurso e atividade|Separe conteúdo para consulta de interação que registra participação.', 'Identifique seu papel|Observe como permissões alteram edição, avaliação e visualização.', 'Escolha uma primeira tarefa|Use a busca do portal para abrir uma orientação compatível com seu objetivo.'],
  'comece-por-aqui/perfil-e-preferencias.md': ['Abra o menu do usuário|Localize Perfil e Preferências no menu associado à conta.', 'Revise dados editáveis|Atualize somente informações autorizadas e confirme o que vem do sistema institucional.', 'Configure mensagens e notificações|Escolha canais e frequência conforme urgência e volume.', 'Teste a nova preferência|Gere uma situação segura ou aguarde um evento para confirmar o comportamento.'],
  'comunicacao/avisos-e-mensagens.md': ['Escolha entre aviso e mensagem|Use aviso para comunicação ampla do curso e mensagem para contato direcionado.', 'Escreva assunto e ação esperada|Comece pela informação principal, prazo e destino.', 'Revise destinatários|Confirme curso, grupo e pessoas antes de enviar.', 'Verifique publicação e notificação|Confira o registro no Moodle e considere preferências individuais.'],
  'comunicacao/calendario-e-eventos.md': ['Liste os eventos esperados|Relacione prazos de atividades, eventos do curso e compromissos pessoais.', 'Abra o calendário correto|Confira filtros e o contexto em que o evento será criado.', 'Defina data, duração e descrição|Use fuso horário e instruções coerentes com a atividade vinculada.', 'Compare calendário e atividade|Garanta que mudanças de prazo também atualizem a fonte correta.'],
  'comunicacao/colaboracao.md': ['Defina o produto coletivo|Explique o que será construído e como contribuições serão combinadas.', 'Escolha a atividade adequada|Compare Fórum, Wiki, Base de dados e Glossário pelo tipo de interação.', 'Distribua papéis e etapas|Defina contribuição inicial, revisão, síntese e responsabilidade final.', 'Acompanhe processo e autoria|Use registros com responsabilidade e ofereça feedback durante a construção.'],
  'comunicacao/mediacao-foruns.md': ['Prepare a abertura|Publique questão, critérios de contribuição e regra de convivência.', 'Acompanhe sem centralizar|Use perguntas de aprofundamento e conecte contribuições entre participantes.', 'Intervenha em dúvidas e conflitos|Diferencie equívoco conceitual, problema técnico e conduta inadequada.', 'Produza uma síntese|Retome evidências, esclareça pontos e indique a próxima ação.'],
  'comunicacao/notificacoes.md': ['Identifique a origem do evento|Descubra qual atividade ou ação está gerando a notificação.', 'Abra as preferências|Localize as opções de notificação no menu da conta.', 'Escolha canal e estado|Ajuste web, e-mail ou móvel para conectado e desconectado, quando disponíveis.', 'Confirme com um evento seguro|Teste sem gerar mensagens em massa e verifique também filtros de e-mail.'],
  'organizacao-do-curso/backup-e-restauracao.md': ['Defina o escopo do backup|Decida se precisa de atividades, blocos, banco de questões e dados de usuários autorizados.', 'Gere e revise o arquivo|Percorra as etapas, confira o resumo e aguarde a conclusão.', 'Armazene de forma protegida|Baixe somente quando necessário e aplique retenção institucional.', 'Teste a restauração|Use curso de teste e confira estrutura, links, questões, notas e dados incluídos.'],
  'organizacao-do-curso/blocos.md': ['Defina a função do bloco|Escolha informação que precisa permanecer visível fora do conteúdo central.', 'Adicione no contexto correto|Ative edição e selecione o bloco permitido pelo ambiente.', 'Configure posição e visibilidade|Revise página, região, peso e público conforme as opções disponíveis.', 'Teste em diferentes telas|Garanta que o bloco não esconda conteúdo nem dependa de coluna ausente no celular.'],
  'organizacao-do-curso/configurar-curso.md': ['Revise identidade e datas|Confira nome, nome breve, início, término e visibilidade.', 'Escolha formato e aparência|Defina seções, layout, idioma e arquivos com base no percurso.', 'Configure grupos e acompanhamento|Aplique modalidade e conclusão apenas quando forem usadas.', 'Teste o curso como participante|Verifique acesso, navegação, calendário, notas e itens ocultos.'],
  'organizacao-do-curso/editar-mover-duplicar.md': ['Ative a edição e localize o item|Confirme título, seção e atividade antes de agir.', 'Escolha editar, mover ou duplicar|Use a ação mínima e preserve o original quando precisar comparar.', 'Revise a cópia ou nova posição|Atualize nome, datas, restrições, grupos e conclusão.', 'Teste links e sequência|Confirme que o estudante encontra somente a versão correta.'],
  'organizacao-do-curso/formatos-e-secoes.md': ['Mapeie unidades e marcos|Defina como semanas ou temas representam o percurso.', 'Escolha o formato do curso|Compare organização, navegação e quantidade de conteúdo por seção.', 'Crie e nomeie seções|Use títulos informativos e resumos com próxima ação.', 'Teste rolagem e índice|Confira orientação em computador, celular e retomada de estudo.'],
  'organizacao-do-curso/grupos-e-agrupamentos.md': ['Defina os arranjos necessários|Liste equipes, turmas e combinações usadas em cada atividade.', 'Crie grupos e confira membros|Use nomes estáveis e revise participantes sem grupo.', 'Monte agrupamentos|Associe conjuntos de grupos para diferentes contextos.', 'Aplique e teste nas atividades|Compare grupos separados, visíveis e restrição de acesso.'],
  'organizacao-do-curso/integracao-suap.md': ['Identifique o dado de origem|Registre quais cursos, inscrições, papéis ou grupos vêm do SUAP.', 'Confirme a rotina de sincronização|Verifique frequência, responsável e tratamento de divergências.', 'Evite sobrescrever sem autorização|Descubra se mudanças manuais serão revertidas na próxima execução.', 'Teste e reúna evidências|Use conta autorizada e registre identificadores sem expor dados pessoais.'],
  'organizacao-do-curso/reutilizar-conteudo.md': ['Escolha importar, copiar ou restaurar|Use o mecanismo compatível com o escopo e a política de dados.', 'Selecione somente o necessário|Evite trazer usuários, notas ou bancos inteiros sem finalidade.', 'Atualize contexto e datas|Revise nomes, links, grupos, restrições, conclusão e referências ao período anterior.', 'Teste a nova cópia|Percorra como estudante e confira atividades, questões e Livro de notas.'],
  'organizacao-do-curso/visibilidade-e-acesso.md': ['Defina quem deve acessar|Diferencie ocultação, restrição por condição e permissão por papel.', 'Configure a regra mínima|Use data, grupo, nota ou conclusão somente quando necessária.', 'Revise mensagens de restrição|Decida se a condição será exibida ou totalmente ocultada.', 'Teste perfis e combinações|Confirme acesso antes, durante e depois de cada condição.'],
  'participantes/acompanhamento-individual.md': ['Defina a pergunta de acompanhamento|Escolha qual ação ou dificuldade precisa ser compreendida.', 'Consulte evidências pertinentes|Combine participação, conclusão, entregas, notas e comunicação autorizada.', 'Compare contexto e período|Evite interpretar um evento isolado fora do prazo ou da atividade.', 'Registre a próxima ação|Faça contato respeitoso, ofereça suporte e limite o compartilhamento.'],
  'participantes/consultar.md': ['Abra Participantes no curso|Confirme que está no curso e período corretos.', 'Use filtros com finalidade|Pesquise por nome, papel, grupo, estado ou período quando disponíveis.', 'Leia inscrições e papéis|Diferencie acesso ao curso de associação a grupo e permissão.', 'Proteja e descarte os dados|Evite exportação desnecessária e compartilhe apenas com pessoas autorizadas.'],
  'participantes/inscricoes.md': ['Identifique o método ativo|Diferencie inscrição manual, sincronização de coorte e integração institucional.', 'Confira pessoa, papel e período|Valide identidade, função, início, término e estado.', 'Faça a alteração autorizada|Inscreva, suspenda ou ajuste sem remover histórico indevidamente.', 'Teste acesso e reversibilidade|Confirme o resultado e se uma sincronização poderá sobrescrever a mudança.'],
  'participantes/papeis-e-permissoes.md': ['Defina a ação necessária|Comece pela capacidade que a pessoa precisa exercer no contexto.', 'Identifique o papel e o contexto|Diferencie papel no site, categoria, curso e atividade.', 'Evite elevação ampla|Prefira a menor permissão e o menor contexto suficientes.', 'Teste e registre a atribuição|Use conta autorizada e confirme o que aparece e pode ser alterado.'],
  'participantes/sincronizacao-suap.md': ['Confirme o vínculo institucional|Identifique curso, turma, papel e identificador esperados nos dois sistemas.', 'Verifique a última sincronização|Registre horário, estado e mensagens disponíveis.', 'Compare divergências sem editar em massa|Separe atraso de rotina, dado de origem e falha de associação.', 'Encaminhe evidências ao responsável|Informe identificadores mínimos, curso e horário sem expor credenciais.'],
  'relatorios/atividades.md': ['Defina qual atividade investigar|Comece por uma pergunta sobre uso, envio, tentativa ou resultado.', 'Abra o relatório da própria atividade|Use os filtros e estados específicos em vez de um relatório genérico.', 'Compare eventos e produto|Relacione acesso com publicação, envio, resposta, nota ou feedback.', 'Registre limite e encaminhamento|Explique o que o relatório não comprova e qual ação será tomada.'],
  'relatorios/conclusao.md': ['Confirme os critérios configurados|Leia as condições de cada item antes de interpretar o estado.', 'Abra o relatório de conclusão|Use filtro de grupo e legenda para distinguir estados.', 'Investigue pendências|Verifique nota, envio, tarefa agendada, exceção e possível substituição.', 'Acompanhe sem rotular|Use o dado para oferecer orientação, não como prova isolada de aprendizagem.'],
  'relatorios/escolher-relatorio.md': ['Escreva a pergunta antes de abrir o menu|Defina pessoa, período, atividade e evidência necessária.', 'Escolha a fonte mais direta|Prefira o relatório da atividade quando a pergunta for específica.', 'Aplique o menor conjunto de filtros|Reduza ruído sem excluir casos relevantes.', 'Valide interpretação e privacidade|Registre limites e compartilhe somente o necessário.'],
  'relatorios/logs.md': ['Defina evento, pessoa e período|Formule uma hipótese verificável antes de consultar registros.', 'Abra Logs e aplique filtros|Selecione curso, participante, data, atividade e ação quando disponíveis.', 'Leia cada evento literalmente|Diferencie visualizar, enviar, atualizar, baixar e outras ações.', 'Exporte somente se autorizado|Minimize dados e mantenha arquivo pelo tempo institucional necessário.'],
  'relatorios/monitoramento-responsavel.md': ['Defina finalidade legítima|Explique por que o acompanhamento é necessário e quem será beneficiado.', 'Use evidências proporcionais|Colete somente eventos e resultados relacionados à pergunta.', 'Evite inferências automáticas|Não transforme ausência de clique em desinteresse ou dificuldade confirmada.', 'Comunique com transparência|Informe uso dos dados, limite acesso e ofereça canal de esclarecimento.'],
  'relatorios/notas.md': ['Escolha relatório do avaliador ou usuário|Use a matriz para conferência e a visão individual para experiência do estudante.', 'Verifique origem e estado do item|Identifique atividade, nota manual, ocultação, bloqueio e substituição.', 'Compare subtotal e total|Revise categoria, agregação, pesos e valores vazios.', 'Confira feedback e visibilidade|Garanta que o estudante vê exatamente o que foi liberado.'],
  'relatorios/participacao.md': ['Escolha atividade e ação|Defina se precisa de visualização, publicação, envio ou outro evento disponível.', 'Selecione período e papel|Aplique filtros coerentes com a turma e o prazo da atividade.', 'Compare com outra evidência|Relacione participação a produto, nota ou feedback sem presumir aprendizagem.', 'Use a ação em massa com cautela|Revise destinatários e mensagem antes de qualquer contato.'],
  'solucao-de-problemas/acesso.md': ['Registre a mensagem e o horário|Copie o erro sem incluir senha, token ou código de autenticação.', 'Confirme endereço e conta|Verifique domínio institucional, usuário correto e estado da conexão.', 'Teste recuperação e outro navegador|Use somente os fluxos oficiais e uma janela privada quando apropriado.', 'Encaminhe evidências mínimas|Informe ambiente, horário, navegador e resultado dos testes ao suporte.'],
  'solucao-de-problemas/arquivo-nao-abre.md': ['Identifique arquivo e comportamento|Registre nome, tipo, tamanho e se ocorre abertura, download ou erro.', 'Teste o próprio arquivo|Baixe, verifique integridade e tente em aplicativo compatível.', 'Compare navegador e dispositivo|Desative bloqueios apenas de forma segura e teste outra rede quando autorizado.', 'Revise publicação e alternativa|Confirme permissões, aparência e ofereça formato acessível equivalente.'],
  'solucao-de-problemas/atividade-indisponivel.md': ['Confirme curso, pessoa e horário|Descubra quem não vê o item e desde quando.', 'Revise visibilidade e datas|Verifique ocultação, abertura, fechamento e seção do curso.', 'Analise restrições e grupos|Leia todas as condições e combinações aplicadas.', 'Teste com o mesmo perfil|Use conta autorizada e registre qual condição impede o acesso.'],
  'solucao-de-problemas/conclusao-nao-registrada.md': ['Leia a condição exata|Confirme o que precisa ser visualizado, enviado, publicado ou avaliado.', 'Verifique evidência e nota|Compare tentativa, envio, nota para aprovação e visibilidade.', 'Considere processamento agendado|Aguarde o intervalo previsto e verifique a rotina responsável.', 'Revise substituições no relatório|Identifique estado manual e registre correção autorizada.'],
  'solucao-de-problemas/envio-tarefa.md': ['Registre o estado da Tarefa|Confira abertura, entrega, data limite e eventual exceção.', 'Valide tipo e tamanho do envio|Compare arquivo, quantidade, extensão e limite configurados.', 'Revise rascunho e confirmação|Descubra se falta clicar em Enviar ou se a tentativa está bloqueada.', 'Preserve evidências e tente com arquivo fictício|Não apague o envio original antes de registrar mensagem, horário e estado.'],
  'solucao-de-problemas/grupos.md': ['Confirme membros e múltiplas associações|Revise quem está sem grupo ou pertence a mais de uma equipe.', 'Leia modalidade e agrupamento|Compare grupos separados, visíveis e conjunto selecionado.', 'Diferencie interação de acesso|Verifique também restrições por grupo ou agrupamento.', 'Teste com duas contas fictícias|Compare o que cada grupo vê, publica e entrega.'],
  'solucao-de-problemas/nota-nao-aparece.md': ['Confirme se a atividade gerou nota|Verifique correção pendente, estado da tentativa e método de avaliação.', 'Abra o item no Livro de notas|Procure ocultação, bloqueio, substituição e categoria.', 'Compare relatório do avaliador e usuário|Diferencie valor calculado de informação liberada.', 'Revise aprovação e conclusão|Confira limiar, visibilidade e dependências conectadas.'],
  'solucao-de-problemas/questionario.md': ['Registre tentativa e momento|Identifique se o problema ocorre ao abrir, responder, enviar ou revisar.', 'Revise tempo, datas e exceções|Compare condições da turma, usuário e grupo.', 'Verifique estado e questões|Procure tentativa em andamento, encerrada, discursiva ou sem correção.', 'Teste revisão e nota|Confirme o que deveria aparecer naquele momento e preserve a tentativa existente.'],
  'solucao-de-problemas/solicitar-suporte.md': ['Descreva o objetivo e o sintoma|Explique o que tentava fazer, resultado esperado e resultado observado.', 'Reúna contexto mínimo|Informe curso, atividade, horário, navegador e perfil sem enviar credenciais.', 'Produza captura segura|Oculte nomes, notas, e-mails, endereços e qualquer dado desnecessário.', 'Registre testes já realizados|Liste passos e resultados para evitar repetição e acelerar o diagnóstico.'],
  'solucao-de-problemas/video.md': ['Identifique o tipo de vídeo|Diferencie arquivo, link e incorporação externa.', 'Teste conexão, navegador e permissão|Compare janela privada, outro dispositivo e política de conteúdo.', 'Verifique legenda e alternativa|Garanta acesso ao conteúdo mesmo quando a reprodução falha.', 'Revise privacidade e provedor|Confirme consentimento, cookies, domínio autorizado e disponibilidade.']
}

const sectionFallback = {
  atividades: ['Planeje a experiência|Relacione objetivo, participação, acompanhamento e avaliação.', 'Configure e teste|Revise campos específicos e percorra a visão do participante.', 'Acompanhe e ajuste|Use evidências da própria atividade e ofereça feedback.'],
  recursos: ['Defina o propósito|Escolha o recurso pela experiência de leitura ou acesso.', 'Configure o conteúdo|Revise campos próprios, aparência, acesso e conclusão.', 'Teste como estudante|Confira legibilidade, navegação e acessibilidade.']
}

const escapeAttr = (value) => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
const slugLabel = (value) => value.replace(/\.md$/, '').split('/').pop().replaceAll('-', ' ')

function internalLinks(source, current) {
  const links = [...source.matchAll(/\[([^\]]+)\]\((\/[^)#?]+)(?:#[^)]+)?\)/g)]
    .map((match) => ({ title: match[1], href: match[2] }))
    .filter((item, index, all) => item.href !== current && all.findIndex((candidate) => candidate.href === item.href) === index)
  return links.slice(0, 3)
}

function relatedMarkup(source, relative, section) {
  const route = `/${relative.replace(/index\.md$/, '').replace(/\.md$/, '.html')}`
  const links = internalLinks(source, route)
  if (links.length < 2) links.push({ title: `Visão geral de ${section.replaceAll('-', ' ')}`, href: `/${section}/` })
  if (links.length < 2) links.push({ title: 'Glossário Moodle', href: '/glossario/' })
  return `<RelatedContent :items='${JSON.stringify(links.slice(0, 3).map((item) => ({ ...item, description: 'Aprofunde esta decisão no contexto do curso.' })))}' />`
}

function videoMarkup(title, steps, description) {
  const topics = steps.length ? steps.map((step) => step.split('|')[0]) : ['Reconhecer o contexto', 'Aplicar a orientação', 'Testar o resultado']
  return `<VideoSection title="${escapeAttr(title)} — demonstração guiada" description="${escapeAttr(description)}" duration="6–9 minutos" audience="Público indicado na página" status="em-producao" objective="Demonstrar o procedimento em um curso de teste, sem dados pessoais." :script='${JSON.stringify(topics)}' />`
}

function stepMarkup(steps) {
  return `<StepByStep>\n${steps.map((entry, index) => {
    const [title, description] = entry.split('|')
    return `  <StepItem number="${index + 1}" title="${escapeAttr(title)}" description="${escapeAttr(description)}" expected="A decisão “${escapeAttr(title)}” foi registrada e conferida no perfil destinatário." />`
  }).join('\n')}\n</StepByStep>`
}

let changed = 0
for (const file of walk(docsRoot, '.md')) {
  const relative = path.relative(docsRoot, file).replaceAll('\\', '/')
  if (relative === 'index.md' || relative.endsWith('/index.md')) continue
  let source = fs.readFileSync(file, 'utf8')
  const meta = frontmatter(source) || {}
  const section = relative.split('/')[0]
  const isComparison = section === 'comparacoes'
  const steps = plans[relative] || sectionFallback[section] || []
  const additions = []

  const genericExample = /<ExampleBox>Em um curso de demonstração,[\s\S]*?<\/ExampleBox>/
  if (genericExample.test(source)) {
    const subject = String(meta.title || slugLabel(relative)).toLowerCase()
    source = source.replace(genericExample, `<ExampleBox>Em um curso de teste, aplique **${subject}** a uma situação fictícia, registre a configuração escolhida e compare a visão do professor com a do participante antes de usar dados reais.</ExampleBox>`)
  }

  if (!source.includes('<StepByStep') && steps.length && !isComparison) additions.push(stepMarkup(steps))
  if (!source.includes('<ScreenshotPlaceholder') && !isComparison && section !== 'boas-praticas') {
    additions.push(`<ScreenshotPlaceholder id="${relative.replace(/\.md$/, '').replaceAll('/', '-').replaceAll(/[^a-zA-Z0-9-]/g, '').toUpperCase()}-01" title="Tela principal de ${escapeAttr(String(meta.title || slugLabel(relative)))}" description="Captura do ponto de decisão mais importante desta orientação, após validação institucional." framing="Mostrar somente controles necessários e usar dados fictícios." alt="Tela do Moodle 5.2 relacionada a ${escapeAttr(String(meta.title || slugLabel(relative)).toLowerCase())}." />`)
  }
  if (!source.includes('<Checklist') && !isComparison) {
    const items = steps.length ? steps.map((step) => `${step.split('|')[0]} foi verificado`) : ['Finalidade foi definida', 'Configuração foi testada', 'Resultado foi conferido']
    additions.push(`<Checklist :items='${JSON.stringify(items)}' />`)
  }
  if (!source.includes('<VideoSection')) additions.push(videoMarkup(String(meta.title || slugLabel(relative)), steps, String(meta.description || 'Veja a aplicação no Moodle 5.2.')))
  if (!source.includes('<RelatedContent')) additions.push(relatedMarkup(source, relative, section))

  if (additions.length || genericExample.test(source)) {
    const marker = '\n\n## Amplie esta orientação\n\n'
    source = `${source.trimEnd()}${marker}${additions.join('\n\n')}\n`
    fs.writeFileSync(file, source)
    changed += 1
  }
}

console.log(`Enriquecimento aplicado a ${changed} páginas sem remover o conteúdo existente.`)
